services:
  - type: web
    name: wargame
    runtime: node
    plan: free
    buildCommand: rm -rf node_modules package-lock.json && npm install --no-optional --no-audit --no-fund --legacy-peer-deps && npm run build
    startCommand: npm start    envVars:
      - key: NODE_ENV
        value: production
      - key: VITE_SERVER_URL
        value: https://wargame-dywk.onrender.com
